name: Tests And Build
on:
  push:
    branches: [ master, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm run-script test --coverage
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ./coverage/
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Build and push docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: fourstring/url-shortener-frontend
          tags: latest
